services:
  train:
    build:
      context: .
      dockerfile: Dockerfile_train
    volumes:
      - ./data:/house_price_prediction/data

  predict:
    build:
      context: .
      dockerfile: Dockerfile_stream
    volumes:
      - ./data:/house_price_prediction/data
