services:
  train:
    build:
      context: .
      dockerfile: Dockerfile_train
    volumes:
      - ./data:/house_price_prediction/data
      - ./model:/house_price_prediction/model
      - ./results:/house_price_prediction/results


  predict:
    build:
      context: .
      dockerfile: Dockerfile_stream
    volumes:
      - ./data:/house_price_prediction/data
      - ./model:/house_price_prediction/model
      - ./results:/house_price_prediction/results

volumes:
  data:
  model:
  results: